import { NextApiRequest, NextApiResponse } from 'next'
import OpenAI from 'openai'
import { db } from '@/lib/firebase'
import { getServerSession } from 'next-auth'
import { authOptions } from '../auth/[...nextauth]'

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
})

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  if (req.method !== 'POST') {
    return res.status(405).json({ message: 'Method not allowed' })
  }

  try {
    const session = await getServerSession(req, res, authOptions)

    if (!session?.user?.id) {
      return res.status(401).json({ message: 'Unauthorized' })
    }

    // Check if user has PRO tier
    const userDoc = await db.collection('users').doc(session.user.id).get()
    const userData = userDoc.data()

    if (userData?.tier !== 'PRO') {
      return res.status(403).json({ message: 'AI Chef is a PRO feature. Please upgrade.' })
    }

    const { ingredients, dietaryRestrictions, servings } = req.body

    if (!ingredients || ingredients.length === 0) {
      return res.status(400).json({ message: 'Please provide ingredients' })
    }

    // Use ChatGPT to generate a recipe
    const prompt = `You are a professional chef AI. Create a delicious recipe using ONLY these ingredients from the user's fridge/pantry:

Ingredients available: ${ingredients.join(', ')}
${dietaryRestrictions ? `Dietary restrictions: ${dietaryRestrictions.join(', ')}` : ''}
Servings needed: ${servings || 4}

Create a recipe that:
1. Uses as many of the available ingredients as possible
2. Is realistic and achievable for home cooks
3. Provides clear step-by-step instructions
4. Includes cooking time estimates
5. Respects dietary restrictions

Format as JSON:
{
  "name": string,
  "description": string,
  "prepTime": number (minutes),
  "cookTime": number (minutes),
  "servings": number,
  "difficulty": "Easy" | "Medium" | "Hard",
  "ingredients": [
    {
      "name": string,
      "quantity": string,
      "unit": string
    }
  ],
  "instructions": [string],
  "estimatedCalories": number,
  "tips": string
}`

    const completion = await openai.chat.completions.create({
      model: 'gpt-4o-mini', // Basic model for simple recipe generation
      messages: [
        {
          role: 'system',
          content: 'You are a professional chef AI assistant specializing in creative home cooking. You help users make delicious meals with ingredients they already have.'
        },
        {
          role: 'user',
          content: prompt
        }
      ],
      response_format: { type: 'json_object' },
      temperature: 0.8,
    })

    const recipe = JSON.parse(completion.choices[0].message.content || '{}')

    // Save the generated recipe to Firestore
    const recipeRef = await db.collection('recipes').add({
      userId: session.user.id,
      name: recipe.name,
      description: recipe.description,
      ingredients: recipe.ingredients,
      instructions: recipe.instructions,
      prepTime: recipe.prepTime,
      cookTime: recipe.cookTime,
      servings: recipe.servings,
      calories: recipe.estimatedCalories,
      difficulty: recipe.difficulty,
      dietaryTags: dietaryRestrictions || [],
      source: 'GENERATED',
      autoGenerated: true,
      isPublic: false,
      usageCount: 0,
      likesCount: 0,
      viewsCount: 0,
      createdAt: new Date(),
      updatedAt: new Date(),
    })

    return res.status(200).json({
      message: 'Recipe generated successfully!',
      recipe: {
        id: recipeRef.id,
        ...recipe,
      }
    })

  } catch (error: any) {
    console.error('AI recipe generation error:', error)
    
    if (error.code === 'insufficient_quota') {
      return res.status(500).json({ 
        message: 'OpenAI API quota exceeded. Please try again later.' 
      })
    }

    return res.status(500).json({ 
      message: 'Failed to generate recipe',
      error: error.message 
    })
  }
}





