/**
 * iOS App Meal Plan Generation Endpoint
 * Generates meal plans (server-side only)
 * Pro tier users get budget-optimized plans with supermarket discounts
 */

import { NextApiRequest, NextApiResponse } from 'next'
import { verify } from 'jsonwebtoken'
import { prisma } from '@/lib/prisma'
import { generateMealPlan } from '@/lib/openai'
import { supermarketScraper } from '@/lib/supermarket-scraper'
import { z } from 'zod'
import { addDays, startOfDay } from 'date-fns'

const generateMealPlanSchema = z.object({
  days: z.number().min(1).max(14),
  budget: z.number().optional(),
  dietaryRestrictions: z.array(z.string()).optional(),
  startDate: z.string().optional(),
  zipCode: z.string().optional(),
})

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  if (req.method !== 'POST') {
    return res.status(405).json({ message: 'Method not allowed' })
  }

  try {
    // Verify iOS app token
    const authHeader = req.headers.authorization
    if (!authHeader || !authHeader.startsWith('Bearer ')) {
      return res.status(401).json({ message: 'Missing or invalid authorization header' })
    }

    const token = authHeader.substring(7)
    let decoded: any
    
    try {
      decoded = verify(token, process.env.NEXTAUTH_SECRET || 'your-secret-key')
    } catch (error) {
      return res.status(401).json({ message: 'Invalid or expired token' })
    }

    const userId = decoded.userId
    const userTier = decoded.tier

    const params = generateMealPlanSchema.parse(req.body)
    
    let discounts = []
    
    // Pro tier: Get budgeted meal plans with supermarket discounts
    if (userTier === 'PRO' && params.budget && params.zipCode) {
      discounts = await supermarketScraper.getDiscounts(params.zipCode)
      
      // Update discounts if data is stale (older than 1 day)
      const recentDiscount = await prisma.supermarketDiscount.findFirst({
        where: { location: params.zipCode },
        orderBy: { createdAt: 'desc' },
      })
      
      const oneDayAgo = new Date(Date.now() - 24 * 60 * 60 * 1000)
      if (!recentDiscount || recentDiscount.createdAt < oneDayAgo) {
        await supermarketScraper.updateDiscounts(params.zipCode)
        discounts = await supermarketScraper.getDiscounts(params.zipCode)
      }
    } else if (params.budget && userTier === 'FREE') {
      // Free tier users trying to use budget feature
      return res.status(403).json({
        message: 'Budget meal planning with supermarket discounts is a Pro feature',
        upgrade: true,
      })
    }

    // Generate meal plan (server-side only!)
    const generatedMealPlan = await generateMealPlan({
      days: params.days,
      budget: params.budget,
      dietaryRestrictions: params.dietaryRestrictions,
      discounts: discounts.slice(0, 20).map(d => ({
        itemName: d.itemName,
        discountPrice: d.discountPrice,
        storeName: d.storeName,
      })),
    })
    
    const startDate = params.startDate ? new Date(params.startDate) : startOfDay(new Date())
    const endDate = addDays(startDate, params.days - 1)
    
    // Save meal plan to database
    const mealPlan = await prisma.mealPlan.create({
      data: {
        userId,
        name: generatedMealPlan.mealPlan.name,
        startDate,
        endDate,
        budget: params.budget,
        totalCost: generatedMealPlan.mealPlan.totalCost,
      }
    })

    const recipes = []

    // Create recipes and link to meal plan
    for (const day of generatedMealPlan.mealPlan.days) {
      for (const [mealType, mealData] of Object.entries(day.meals)) {
        const recipe = await prisma.recipe.create({
          data: {
            userId,
            name: mealData.name,
            ingredients: mealData.ingredients,
            instructions: mealData.instructions,
            servings: 2,
            autoGenerated: true,
            source: 'GENERATED',
          }
        })

        await prisma.mealPlanRecipe.create({
          data: {
            mealPlanId: mealPlan.id,
            recipeId: recipe.id,
            dayOfWeek: day.day,
            mealType: mealType.toUpperCase() as any,
          }
        })

        recipes.push({
          ...recipe,
          dayOfWeek: day.day,
          mealType: mealType.toUpperCase(),
        })
      }
    }

    return res.status(200).json({
      mealPlan: {
        id: mealPlan.id,
        name: mealPlan.name,
        startDate: mealPlan.startDate,
        endDate: mealPlan.endDate,
        budget: mealPlan.budget,
        totalCost: mealPlan.totalCost,
        recipes,
      },
      discountsUsed: discounts.length,
    })
  } catch (error) {
    if (error instanceof z.ZodError) {
      return res.status(400).json({ message: 'Invalid input', errors: error.errors })
    }
    
    console.error('iOS meal plan generation error:', error)
    return res.status(500).json({ message: 'Failed to generate meal plan' })
  }
}







